version: '3.9'
services:
  database:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    env_file: 
      - .env
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network

  server:
    build:
      dockerfile: local.dockerfile
    volumes:
      - /app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - network

volumes:
  database:
    name: database

networks:
   network: